<a href="https://colab.research.google.com/github/Machine-Learning-Visao-Computacional-T1/CodigosDeAula-Python-Dados-/blob/main/Semana2/Dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import seaborn as sns  # Biblioteca de visualização que possui datasets de estudo embutidos

In [ ]:
print("1. Carregando o dataset de estudo diretamente da biblioteca...")
# O método 'load_dataset' traz os dados prontos para uso em formato de tabela
#df = sns.load_dataset('iris')
df = pd.read_csv('dengue.csv', sep=';')

1. Carregando o dataset de estudo diretamente da biblioteca...

In [ ]:
print("\n--- VISÃO GERAL DOS DADOS ---")
display(df.head(200))

--- VISÃO GERAL DOS DADOS ---

   Idade Sexo  Peso   Manchas  Temp.  Num.Inter. Estado Diagnóstico
0     37    M    73   Grandes   38.0           2     SP      Doente
1     18    F    79  Pequenas   39.5           4     MG    Saudável
2     40    M    68  Pequenas   38.0           0     RS      Doente
3     18    F    90    Médias   38.5          11     MG      Doente
4     50    M    78   Grandes   37.6           2     PE    Saudável
5     54    M    56   Pequeas   38.0           3     RJ    Saudável
6     72    M    67   Grandes   39.0           0     AM      Doente
7     22    M    78    Médias   38.4           6     GO    Saudável

In [ ]:
print("\n2. Separando as Features (X) e o Rótulo (y)...")
# Queremos prever a especie flor
X = df.drop(columns=['Manchas'])

2. Separando as Features (X) e o Rótulo (y)...

In [ ]:
print(X)

   Idade Sexo  Peso  Temp.  Num.Inter. Estado Diagnóstico
0     37    M    73   38.0           2     SP      Doente
1     18    F    79   39.5           4     MG    Saudável
2     40    M    68   38.0           0     RS      Doente
3     18    F    90   38.5          11     MG      Doente
4     50    M    78   37.6           2     PE    Saudável
5     54    M    56   38.0           3     RJ    Saudável
6     72    M    67   39.0           0     AM      Doente
7     22    M    78   38.4           6     GO    Saudável

In [ ]:
# y = Apenas a coluna 'tip' (Nosso gabarito)
y = df['Manchas']

In [ ]:
print(y)

0     Grandes
1    Pequenas
2    Pequenas
3      Médias
4     Grandes
5     Pequeas
6     Grandes
7      Médias
Name: Manchas, dtype: object

In [ ]:
print("\n--- AS FEATURES (X) ---")
display(X.head(3))

--- AS FEATURES (X) ---

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2

In [ ]:
print("\n--- O RÓTULO (y) ---")
display(y.head(3))

--- O RÓTULO (y) ---

0    setosa
1    setosa
2    setosa
Name: species, dtype: object