<a href="https://colab.research.google.com/github/Machine-Learning-Visao-Computacional-T1/CodigosDeAula-Python-Dados-/blob/main/Semana5/Semana_5_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Padrão de definição em python para engenharia de dados:

In [1]:
TAXA = 0.15

In [2]:
def calcular_imposto(valor: float, taxa: float = 0.15) -> float:
    """
    Calcula o imposto sobre um valor com uma taxa padrão de 15%.
    Retorna o valor final com o imposto aplicado.
    """
    imposto = valor * taxa
    valor_final = valor + imposto
    return valor_final # O 'return' É preferivel retornar em variável

# Usando a função:
preco_notebook = calcular_imposto(3500.00,TAXA)
print(f"Preço final: R$ {preco_notebook}")

Preço final: R$ 4025.0

## Função Lambda:

In [3]:
# Função Clássica
def quadrado(x):
    return x ** 2

# Mesma função, versão Lambda
quadrado_lambda = lambda x: x ** 2

print(quadrado_lambda(5)) # Saída: 25

# APLICAÇÃO REAL: Usando Lambda com a função map() para aplicar a regra em uma lista inteira
precos_sujos = [10.50, 20.00, 35.99]
precos_com_desconto = list(map(lambda p: p * 0.90, precos_sujos))

print(precos_com_desconto) # Saída: [9.45, 18.0, 32.391]

25
[9.450000000000001, 18.0, 32.391000000000005]

## Modularização: (Realizar teste no vscode)

In [4]:
# --- DENTRO DO ARQUIVO: minhas_ferramentas.py ---
def limpar_moeda(valor_str):
    return float(valor_str.replace('R$', '').replace(',', '.'))

# --- DENTRO DO ARQUIVO PRINCIPAL (main.py) ---
# Importando a função específica que criamos
#from minhas_ferramentas import limpar_moeda

valor_texto = "R$ 1500,50"
valor_matematico = limpar_moeda(valor_texto)
print(valor_matematico)

1500.5

## Expressões Regulares(REGEX)

In [5]:
import re

texto_chat = """
Atendente: O notebook gamer custa R$ 4.500,00 na loja física.
Cliente: Mas no site vi por R$3999,90!
Atendente: Consigo fazer por R$ 4.000,00 se pagar à vista.
"""

# 1. Encontrando os padrões de dinheiro no texto
padrao_dinheiro = r'R\$\s*[\d\.,]+'
precos_brutos = re.findall(padrao_dinheiro, texto_chat)

print("Preços encontrados no chat:", precos_brutos)
# Saída: ['R$ 4.500,00', 'R$3999,90', 'R$ 4.000,00']

# 2. Transformando em Float (Opcional, mas nível Sênior!)
precos_matematicos = []
for p in precos_brutos:
    # Remove R$, espaços e pontos de milhar, e troca a vírgula por ponto decimal
    p_limpo = re.sub(r'[R\$\s\.]', '', p).replace(',', '.')
    precos_matematicos.append(float(p_limpo))

print("Preços prontos para o Numpy:", precos_matematicos)

Preços encontrados no chat: ['R$ 4.500,00', 'R$3999,90', 'R$ 4.000,00']
Preços prontos para o Numpy: [4500.0, 3999.9, 4000.0]

In [6]:
import re

texto_cliente = "Nome: João, Contato: (11) 98888-7777, CPF: 123.456.789-00!"

# 1. Extraindo apenas os números do CPF (Limpando pontuação)
cpf_limpo = re.sub(r'\D', '', "123.  456.789-00") # Substitui o que não for número por VAZIO ('')
print("CPF Limpo:", cpf_limpo) # Saída: 12345678900

# 2. Extraindo o telefone ignorando o texto ao redor
padrao_telefone = r'\(\d{2}\)\s\d{5}-\d{4}' # Busca: (XX) XXXXX-XXXX
telefone = re.findall(padrao_telefone, texto_cliente)
print("Telefone Extraído:", telefone)

CPF Limpo: 12345678900
Telefone Extraído: ['(11) 98888-7777']

In [18]:
import re

relatorio_estoque = """
Registro A: Lote-8849 - TV 50 Polegadas - Saldo: 45 unidades - Valor: 3.50
Registro B: Lote-1023 - Geladeira Frost Free - Saldo: 12 unidades - Valor: 20.00
Registro C: Lote-9921 - Micro-ondas - Saldo: 8 unidades - Valor: 30.60
"""

# ---------------------------------------------------------
# DESAFIO 1: Extrair apenas os números dos Lotes
# ---------------------------------------------------------
# Padrão: Procure a palavra "Lote-", seguida de um ou mais números (\d+).
# Como os números estão entre parênteses, o Python ignora o "Lote-" na hora de salvar!

lotes_extraidos = re.findall(padrao_lote, relatorio_estoque)
print("Números dos Lotes (IDs):", lotes_extraidos)
# Saída: ['8849', '1023', '9921']

# ---------------------------------------------------------
# DESAFIO 2: Extrair apenas as quantidades do saldo
# ---------------------------------------------------------
# Padrão: Procure números (\d+) seguidos de espaços (\s*) e a palavra "unidades".
# Novamente, os parênteses capturam SÓ o número.
padrao_saldo = r'(\d+)\s*unidades'

saldos_extraidos = re.findall(padrao_saldo, relatorio_estoque)
print("Quantidades em Estoque:", saldos_extraidos)
# Saída: ['45', '12', '8']
print(type(saldos_extraidos[0]))

# ---------------------------------------------------------
# DESAFIO 3: Extrair apenas os valores unitarios
# ---------------------------------------------------------
# Padrão: Procure o padrao Valor: digito.digito
padrao_valor = r'Valor:\s*(\d+.\d+)'

valor_extraidos = re.findall(padrao_valor, relatorio_estoque)
print("Valor Unitario:", valor_extraidos)
# Saída: ['3.50', '20.00', '30.60']
print(type(saldos_extraidos[0]))

# Bônus Sênior: Convertendo a lista de textos extraídos para uma lista de inteiros (Numpy-ready)
saldos_inteiros = list(map(int, saldos_extraidos))
print("Saldos prontos para cálculos:", saldos_inteiros)
print(type(saldos_inteiros))

Números dos Lotes (IDs): ['8849', '1023', '9921']
Quantidades em Estoque: ['45', '12', '8']
<class 'str'>
Valor Unitario: ['3.50', '20.00', '30.60']
<class 'str'>
Saldos prontos para cálculos: [45, 12, 8]
<class 'list'>

## Numpy

In [20]:
import numpy as np

# Convertendo uma lista lenta em um Array super rápido
lista_python = [10, 20, 30, 40]
array_numpy = np.array(lista_python)

print(type(array_numpy)) # Saída: <class 'numpy.ndarray'>

array = np.array([10, 20, 30, 40])
print(array)

<class 'numpy.ndarray'>
[10 20 30 40]

In [31]:
import numpy as np

# Simulando um Dataset real: [Idade, Salário, Comprou? (1=Sim, 0=Não)]
dataset = np.array([
    [25, 5000, 1],
    [30, 8000, 0],
    [45, 12000, 1],
    [22, 2500, 0]
])

print("Tabela Completa:\n", dataset)

# Slicing (Fatiamento): Separando as Características (X) do Alvo (y)
# [linhas, colunas] -> ':' significa TODAS. ':-1' significa TODAS MENOS A ÚLTIMA
X = dataset[:, :-1]
y = dataset[:, -1]  # Pega APENAS a última

print("\nMatriz de Características (X):\n", X)
print("\nVetor Alvo (y):\n", y)

Tabela Completa:
 [[   25  5000     1]
 [   30  8000     0]
 [   45 12000     1]
 [   22  2500     0]]

Matriz de Características (X):
 [[   25  5000]
 [   30  8000]
 [   45 12000]
 [   22  2500]]

Vetor Alvo (y):
 [1 0 1 0]

## Vetorização e Broadcasting

In [23]:
import numpy as np

precos = np.array([100.0, 250.0, 300.0])

# Sem Vetorização (Lento - Estilo Python Clássico)
precos_com_juros = []
for p in precos:
    precos_com_juros.append(p * 1.10)
print(precos_com_juros)

# COM Vetorização e Broadcasting (Rápido - Estilo Numpy Sênior)
# Multiplicamos o array inteiro por um número escalar. O Numpy "estica" o 1.10 para todos!
precos_finais = precos * 1.10

print(precos_finais) # Saída: [110. 275. 330.]

[np.float64(110.00000000000001), np.float64(275.0), np.float64(330.0)]
[110. 275. 330.]

In [25]:
import numpy as np

# Broadcasting: Multiplicando preços de produtos em 2 lojas diferentes por taxas de impostos
# 2 Lojas (Linhas), 3 Produtos (Colunas)
precos_lojas = np.array([
    [100, 200, 300],
    [150, 250, 350]
])

# Taxas de imposto para os 3 produtos (Vetor 1D)
taxas = np.array([1.10, 1.15, 1.05])

# O Numpy "estica" o vetor de taxas para as duas lojas automaticamente!
precos_finais = precos_lojas * taxas

print("Preços com imposto aplicado em todas as lojas simultaneamente:\n", precos_finais)

Preços com imposto aplicado em todas as lojas simultaneamente:
 [[110.  230.  315. ]
 [165.  287.5 367.5]]

## Indexação e Slicing

In [29]:
import numpy as np

# Simulando um Dataset: [Idade, Renda, Comprou_o_Produto?]
# Temos 4 clientes (linhas) e 3 informações (colunas)
dataset = np.array([
    [25,5000, 1],
   [30, 8000, 0],
   [45, 12000, 1],
   [22, 2500, 0]
])

print(dataset)

print("--- INDEXAÇÃO BÁSICA ---")
# Pegando um dado específico: Linha 2 (índice 1), Coluna 1 (índice 0)
print("Idade do Cliente 2:", dataset[1, 0])

# Pegando uma linha inteira (O perfil do Cliente 3)
print("Perfil do Cliente 3:", dataset[2, :]) # O ':' sozinho significa "TUDO"

[[   25  5000     1]
 [   30  8000     0]
 [   45 12000     1]
 [   22  2500     0]]
--- INDEXAÇÃO BÁSICA ---
Idade do Cliente 2: 30
Perfil do Cliente 3: [   45 12000     1]

In [30]:

print("\n--- O FATIAMENTO PARA MACHINE LEARNING ---")
# X (Características): Queremos TODAS as linhas (:), e TODAS as colunas EXCETO a última (:-1)
X = dataset[:, :-1]
print("Matriz X (As regras do jogo):\n", X)

# y (Alvo/Target): Queremos TODAS as linhas (:), mas APENAS a última coluna (-1)
y = dataset[:, -1]
print("\nVetor y (O gabarito final):\n", y)

--- O FATIAMENTO PARA MACHINE LEARNING ---
Matriz X (As regras do jogo):
 [[   25  5000]
 [   30  8000]
 [   45 12000]
 [   22  2500]]

Vetor y (O gabarito final):
 [1 0 1 0]

## Mascara Booleana

In [32]:
import numpy as np

idades = np.array([15, 22, 17, 35, 60, 12])

# 1. Filtro Direto (Máscara)
maiores_de_idade = idades[idades >= 18]
print("Filtrado apenas maiores:", maiores_de_idade)

# 2. A função np.where (O 'IF' superpoderoso)
# Sintaxe: np.where(condicao, valor_se_verdadeiro, valor_se_falso)
categorias = np.where(idades >= 18, "Adulto", "Jovem")
print("Categorização rápida:", categorias)

Filtrado apenas maiores: [22 35 60]
Categorização rápida: ['Jovem' 'Adulto' 'Jovem' 'Adulto' 'Adulto' 'Jovem']

## Estatistica básica

In [34]:
import numpy as np

# Dados simulados de vendas
vendas = np.array([80.0, 120.5,150.0, 300.0, 450.2])

print(f"Média das Vendas: R$ {np.mean(vendas):.2f}")
print(f"Mediana (Valor central): R$ {np.median(vendas):.2f}")
print(f"Desvio Padrão (Variação): R$ {np.std(vendas):.2f}")
print(f"Soma Total de Vendas: R$ {np.sum(vendas):.2f}")

teste = np.array([[1, 2, 3],
                  [4, 5, 6]])
print("Teste Soma Coluna:", np.sum(teste, axis=0))
print("Teste Soma Linha:", np.sum(teste, axis=1))

Média das Vendas: R$ 220.14
Mediana (Valor central): R$ 150.00
Desvio Padrão (Variação): R$ 136.96
Soma Total de Vendas: R$ 1100.70
Teste Soma Coluna: [5 7 9]
Teste Soma Linha: [ 6 15]

## Matriz e Reshape

In [37]:
import numpy as np

# Temos um vetor de 6 números (Array 1D)
dados = np.array([10, 20, 30, 40, 50, 60])
print("Dimensão original:", dados.shape) # (6,)

# O Algoritmo de ML exige 2D (Linhas e Colunas).
# O método .reshape() remodela a matriz sem alterar os dados.
# O '-1' pede para o Numpy calcular automaticamente as linhas, criando 1 coluna
dados_para_ml = dados.reshape(-1, 1)

print("Dimensão para ML:\n", dados_para_ml)
# Saída: Matriz com 6 linhas e 1 coluna (2D)
print("Dimensão para ML reshape:", dados_para_ml.shape)

Dimensão original: (6,)
Dimensão para ML:
 [[10]
 [20]
 [30]
 [40]
 [50]
 [60]]
Dimensão para ML reshape: (6, 1)

In [40]:
import numpy as np

# Simulando um Dataset: [Idade, Salário, Anos_Estudo, Comprou?]
dataset = np.array([
    [25, 5000, 4, 1],
    [30, 8000, 6, 0],
    [45, 12000, 8, 1],
    [22, 2500, 2, 0]
])

print("--- SEPARANDO OS DADOS ---")
# X: Todas as linhas (:), Todas as colunas exceto a última (:-1)
X = dataset[:, :-1]

# y: Todas as linhas (:), Apenas a última coluna (-1)
y = dataset[:, -1]

# =====================================================================
# A PROVA MATEMÁTICA (Analisando as Dimensões)
# O atributo .ndim mostra a dimensão real do array.
# O atributo .shape mostra o formato exato (Linhas, Colunas).
# =====================================================================

print("\n ANALISANDO O 'X' (Características):")
print(X)
print(f"-> Dimensão de X: {X.ndim}D")
print(f"-> Formato de X : {X.shape} (4 Linhas, 3 Colunas)")
print("Aprovado para o Scikit-Learn! É uma Matriz bidimensional.")

print("\n ANALISANDO O 'y' (Alvo/Target):")
print(y)
print(f"-> Dimensão de y: {y.ndim}D")
print(f"-> Dimensao de y após reshape: {y.reshape(-1, 1).ndim}")
print(f"-> Formato de y : {y.shape} (4 Elementos, sem largura de coluna)")
print(f"-> Formato de y após reshape: {y.reshape(-1, 1).shape}")
print("Aprovado para o Scikit-Learn! É um Vetor unidimensional.")

--- SEPARANDO OS DADOS ---

 ANALISANDO O 'X' (Características):
[[   25  5000     4]
 [   30  8000     6]
 [   45 12000     8]
 [   22  2500     2]]
-> Dimensão de X: 2D
-> Formato de X : (4, 3) (4 Linhas, 3 Colunas)
Aprovado para o Scikit-Learn! É uma Matriz bidimensional.

 ANALISANDO O 'y' (Alvo/Target):
[1 0 1 0]
-> Dimensão de y: 1D
-> Dimensao de y após reshape: 2
-> Formato de y : (4,) (4 Elementos, sem largura de coluna)
-> Formato de y após reshape: (4, 1)
Aprovado para o Scikit-Learn! É um Vetor unidimensional.

## Pandas

### DF vs Array

In [ ]:
import pandas as pd
import numpy as np

# =====================================================================
# O SEGREDO REVELADO: O Array escondido dentro do DataFrame
# =====================================================================

# 1. Criamos um DataFrame do Pandas (O Terno e Gravata)
df_exemplo = pd.DataFrame({
    'Idade': [25, 30, 45],
    'Salario': [5000.0, 8000.0, 12000.0],
    'Comprou': [1, 0, 1]
})

print("VISÃO PANDAS (O DataFrame):")
print("Temos cabeçalhos, índices e é fácil de ler para um humano.")
display(df_exemplo)

# 2.  Arrancando a "casca" do Pandas
# Usamos o atributo .values (ou .to_numpy()) para ver o que tem dentro daquela tabela
array_secreto = df_exemplo.values

print("\n\n⚙️ VISÃO NUMPY (O Array interno):")
print("Sem cabeçalhos, sem índices, apenas a matriz matemática pura pronta para a IA!")
print(array_secreto)

# Provando matematicamente que é a mesma coisa:
print(f"\nTipo de dado do df_exemplo: {type(df_exemplo)}")
print(f"Tipo de dado depois do .values: {type(array_secreto)}")

VISÃO PANDAS (O DataFrame):
Temos cabeçalhos, índices e é fácil de ler para um humano.

   Idade  Salario  Comprou
0     25   5000.0        1
1     30   8000.0        0
2     45  12000.0        1

⚙️ VISÃO NUMPY (O Array interno):
Sem cabeçalhos, sem índices, apenas a matriz matemática pura pronta para a IA!
[[2.5e+01 5.0e+03 1.0e+00]
 [3.0e+01 8.0e+03 0.0e+00]
 [4.5e+01 1.2e+04 1.0e+00]]

Tipo de dado do df_exemplo: <class 'pandas.core.frame.DataFrame'>
Tipo de dado depois do .values: <class 'numpy.ndarray'>

### Entrada de dados

In [ ]:
import pandas as pd
import io

# =====================================================================
# 1. LENDO DADOS SIMULADOS (Variando entre JSON e CSV)
# =====================================================================
# Simulando JSON (Cadastro de Status dos Clientes)
json_clientes = """
[
    {"ID_Cliente": 1, "Status": "Ativo"},
    {"ID_Cliente": 2, "Status": "Ativo"},
    {"ID_Cliente": 3, "Status": "Inativo"},
    {"ID_Cliente": 4, "Status": "Ativo"},
    {"ID_Cliente": 5, "Status": "Ativo"}
]
"""
df_clientes = pd.read_json(io.StringIO(json_clientes))

# Simulando CSV enriquecido (Agora com Idade, Cliente e Estado para os filtros funcionarem!)
csv_vendas = """ID_Cliente,Cliente,Idade,Data_Venda,Valor,Estado
1,João,35,10/01/2023,5500.0,SP
2,Maria,28,15/01/2023,8000.0,MG
3,Pedro,40,20/02/2023,1200.0,MG
4,Ana,22,25/02/2023,450.0,RJ
5,Lucas,50,01/03/2023,6200.0,MG
1,João,35,15/03/2023,5200.0,SP
"""
df_vendas = pd.read_csv(io.StringIO(csv_vendas))

print("Tabela de Vendas Original:")
display(df_vendas.head())

print("Tabela de Clientes Original:")
display(df_clientes.head())

Tabela de Vendas Original:

   ID_Cliente Cliente  Idade  Data_Venda   Valor Estado
0           1    João     35  10/01/2023  5500.0     SP
1           2   Maria     28  15/01/2023  8000.0     MG
2           3   Pedro     40  20/02/2023  1200.0     MG
3           4     Ana     22  25/02/2023   450.0     RJ
4           5   Lucas     50  01/03/2023  6200.0     MG

Tabela de Clientes Original:

   ID_Cliente   Status
0           1    Ativo
1           2    Ativo
2           3  Inativo
3           4    Ativo
4           5    Ativo

### Comparando Leitura com Pandas e Numpy

In [ ]:
import numpy as np
import pandas as pd
import io

# =====================================================================
# OS NOSSOS DOIS ARQUIVOS SIMULADOS
# =====================================================================
csv_sem_cabecalho = """25,5000.0,1
30,8000.0,0
45,12000.0,1"""

csv_com_cabecalho = """Idade,Salario,Comprou
25,5000.0,1
30,8000.0,0
45,12000.0,1"""

print("==================================================")
print(" 🥊 ROUND 1: LENDO DADOS SEM CABEÇALHO (Pura Matemática)")
print("==================================================")

# NUMPY: Lê perfeitamente, pois só tem números!
matriz_numpy_sem = np.loadtxt(io.StringIO(csv_sem_cabecalho), delimiter=',')
print("\n🟢 NUMPY (Sem Cabeçalho): Sucesso absoluto!")
print(matriz_numpy_sem)

# PANDAS: Vai errar! Como não avisamos, ele "rouba" a primeira linha de dados para virar o título da coluna!
df_pandas_errado = pd.read_csv(io.StringIO(csv_sem_cabecalho))
print("\n🔴 PANDAS (Sem Cabeçalho): Errou! Transformou o cliente de 25 anos em título de coluna:")
display(df_pandas_errado)

# CORREÇÃO PANDAS: Precisamos avisar 'header=None'
df_pandas_corrigido = pd.read_csv(io.StringIO(csv_sem_cabecalho), header=None)
print("\n🟢 PANDAS (Sem Cabeçalho - Corrigido com header=None):")
display(df_pandas_corrigido)


print("\n\n==================================================")
print(" 🥊 ROUND 2: LENDO DADOS COM CABEÇALHO (O Mundo Real)")
print("==================================================")

# NUMPY: Se rodarmos direto, ele quebra! (ValueError: could not convert string to float: 'Idade')
# Precisamos OBRIGATORIAMENTE pular a primeira linha (skiprows=1)
matriz_numpy_com = np.loadtxt(io.StringIO(csv_com_cabecalho), delimiter=',', skiprows=1)
print("\n🟡 NUMPY (Com Cabeçalho): Só funciona se usarmos 'skiprows=1' para ignorar o texto:")
print(matriz_numpy_com)

# PANDAS: Aqui ele brilha! É o comportamento padrão dele.
df_pandas_com = pd.read_csv(io.StringIO(csv_com_cabecalho))
print("\n🟢 PANDAS (Com Cabeçalho): Feito para isso! Reconheceu os nomes das colunas automaticamente:")
display(df_pandas_com)

==================================================
 🥊 ROUND 1: LENDO DADOS SEM CABEÇALHO (Pura Matemática)
==================================================

🟢 NUMPY (Sem Cabeçalho): Sucesso absoluto!
[[2.5e+01 5.0e+03 1.0e+00]
 [3.0e+01 8.0e+03 0.0e+00]
 [4.5e+01 1.2e+04 1.0e+00]]

🔴 PANDAS (Sem Cabeçalho): Errou! Transformou o cliente de 25 anos em título de coluna:

   25   5000.0  1
0  30   8000.0  0
1  45  12000.0  1

🟢 PANDAS (Sem Cabeçalho - Corrigido com header=None):

    0        1  2
0  25   5000.0  1
1  30   8000.0  0
2  45  12000.0  1

==================================================
 🥊 ROUND 2: LENDO DADOS COM CABEÇALHO (O Mundo Real)
==================================================

🟡 NUMPY (Com Cabeçalho): Só funciona se usarmos 'skiprows=1' para ignorar o texto:
[[2.5e+01 5.0e+03 1.0e+00]
 [3.0e+01 8.0e+03 0.0e+00]
 [4.5e+01 1.2e+04 1.0e+00]]

🟢 PANDAS (Com Cabeçalho): Feito para isso! Reconheceu os nomes das colunas automaticamente:

   Idade  Salario  Comprou
0     25   5000.0        1
1     30   8000.0        0
2     45  12000.0        1

### Filtros e Seleções

In [ ]:
# =====================================================================
# 2. FILTROS E SELEÇÕES (.loc, .iloc e Máscaras)
# =====================================================================
print("\n--- 1. Filtro Simples (Valor > 5000) ---")
vendas_altas = df_vendas[df_vendas['Valor'] > 5000]
display(vendas_altas)

print("\n--- 2. Múltiplas Condições (Idade > 30 E Estado == MG) ---")
clientes_alvo = df_vendas[(df_vendas['Idade'] > 30) & (df_vendas['Estado'] == 'MG')]
display(clientes_alvo)

print("\n--- 3. Filtro com .loc (Estado == MG, mostrando só Cliente e Valor) ---")
resumo_mg = df_vendas.loc[df_vendas['Estado'] == 'MG', ['Cliente', 'Valor']]
display(resumo_mg)

print("\n--- 4. Fatiamento com .iloc (Primeiras 3 linhas, Primeiras 3 colunas) ---")
amostra_dados = df_vendas.iloc[0:3, 0:3]
display(amostra_dados)

--- 1. Filtro Simples (Valor > 5000) ---

   ID_Cliente Cliente  Idade  Data_Venda   Valor Estado
0           1    João     35  10/01/2023  5500.0     SP
1           2   Maria     28  15/01/2023  8000.0     MG
4           5   Lucas     50  01/03/2023  6200.0     MG
5           1    João     35  15/03/2023  5200.0     SP

--- 2. Múltiplas Condições (Idade > 30 E Estado == MG) ---

   ID_Cliente Cliente  Idade  Data_Venda   Valor Estado
2           3   Pedro     40  20/02/2023  1200.0     MG
4           5   Lucas     50  01/03/2023  6200.0     MG

--- 3. Filtro com .loc (Estado == MG, mostrando só Cliente e Valor) ---

  Cliente   Valor
1   Maria  8000.0
2   Pedro  1200.0
4   Lucas  6200.0

--- 4. Fatiamento com .iloc (Primeiras 3 linhas, Primeiras 3 colunas) ---

   ID_Cliente Cliente  Idade
0           1    João     35
1           2   Maria     28
2           3   Pedro     40

### Datetime - Datas

In [ ]:
# =====================================================================
# 3. TRABALHANDO COM DATAS (Datetime)
# =====================================================================
# Convertendo texto para data matemática
df_vendas['Data_Venda'] = pd.to_datetime(df_vendas['Data_Venda'], format='%d/%m/%Y')
df_vendas['Mes'] = df_vendas['Data_Venda'].dt.month # Extraindo apenas o mês

print(df_vendas)
print(type(df_vendas))
print(type(df_vendas['Data_Venda']))
df_vendas.info()
df_vendas.head()

   ID_Cliente Cliente  Idade Data_Venda   Valor Estado  Mes
0           1    João     35 2023-01-10  5500.0     SP    1
1           2   Maria     28 2023-01-15  8000.0     MG    1
2           3   Pedro     40 2023-02-20  1200.0     MG    2
3           4     Ana     22 2023-02-25   450.0     RJ    2
4           5   Lucas     50 2023-03-01  6200.0     MG    3
5           1    João     35 2023-03-15  5200.0     SP    3
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID_Cliente  6 non-null      int64
 1   Cliente     6 non-null      object
 2   Idade       6 non-null      int64
 3   Data_Venda  6 non-null      datetime64[ns]
 4   Valor       6 non-null      float64
 5   Estado      6 non-null      object
 6   Mes         6 non-null      int32
dtypes: datetime64[ns](1), float64(1), int32(1), int64(2), object(2)
memory usage: 444.0+ bytes

   ID_Cliente Cliente  Idade Data_Venda   Valor Estado  Mes
0           1    João     35 2023-01-10  5500.0     SP    1
1           2   Maria     28 2023-01-15  8000.0     MG    1
2           3   Pedro     40 2023-02-20  1200.0     MG    2
3           4     Ana     22 2023-02-25   450.0     RJ    2
4           5   Lucas     50 2023-03-01  6200.0     MG    3

## Operacoes Relacionais

In [ ]:
# =====================================================================
# 4. GROUPBY (Agrupamento e Resumo)
# =====================================================================
print("\n--- 5. Faturamento Total por Estado (GroupBy) ---")
faturamento_estado = df_vendas.groupby('Estado')['Valor'].sum().reset_index()
display(faturamento_estado)

--- 5. Faturamento Total por Estado (GroupBy) ---

  Estado    Valor
0     MG  15400.0
1     RJ    450.0
2     SP  10700.0

In [ ]:
# =====================================================================
# 5. MERGE (Cruzamento Relacional / PROCV)
# =====================================================================
print("\n--- 6. Cruzando Vendas com Status dos Clientes (Merge) ---")
df_final = pd.merge(df_vendas, df_clientes, on='ID_Cliente', how='left')
display(df_final)

--- 6. Cruzando Vendas com Status dos Clientes (Merge) ---

   ID_Cliente Cliente  Idade Data_Venda   Valor Estado  Mes   Status
0           1    João     35 2023-01-10  5500.0     SP    1    Ativo
1           2   Maria     28 2023-01-15  8000.0     MG    1    Ativo
2           3   Pedro     40 2023-02-20  1200.0     MG    2  Inativo
3           4     Ana     22 2023-02-25   450.0     RJ    2    Ativo
4           5   Lucas     50 2023-03-01  6200.0     MG    3    Ativo
5           1    João     35 2023-03-15  5200.0     SP    3    Ativo

## Pivot Table

In [ ]:
# =====================================================================
# 6. PIVOT TABLE (Tabela Dinâmica / Visão Matricial)
# =====================================================================
print("\n--- 7. Tabela Dinâmica: Clientes (Linhas) vs Meses (Colunas) ---")
matriz_vendas = df_final.pivot_table(
    values='Valor',
    index='Cliente',
    columns='Mes',
    aggfunc='sum',
    fill_value=0
)
display(matriz_vendas)

--- 7. Tabela Dinâmica: Clientes (Linhas) vs Meses (Colunas) ---

Mes           1       2       3
Cliente
Ana         0.0   450.0     0.0
João     5500.0     0.0  5200.0
Lucas       0.0     0.0  6200.0
Maria    8000.0     0.0     0.0
Pedro       0.0  1200.0     0.0